### ISSUE TITLE
Rule idea: Dissallow return inside each iteratee

### ISSUE THREAD

**Issue by captbaritone** [captbaritone/eslint-plugin-underscore#7]
Many implementations of "each" allow for an early exit from the loop by returning a magic value like "false". Underscore does not offer an early exit. Furthermore, it does not do anything with the each's iteratee's return value.

This rule would disallow returning anything from each's iteratee. It would be good for it to allow a return with no value, to allow people to short-circuit/exit early from the iteratee itself.

**Comment by captbaritone** [comment]
## Valid

```
_.each(items, function(item) {
    if(item.bogus) {
        return;
    }
    myFunc(item);
}
```

## Invalid

```
_.each(items, function(item) {
    if(item.selected) {
        found = item;
        return false;
    }
});
```

**Comment by pwmiller** [comment]
PR has been updated to reflect comments and feedback.  Looking forward to seeing how many instances this catches in our actual code. :)
